### ISSUE TITLE
Drop embed sends after a message is sent

### ISSUE THREAD

**Issue by Cy1der** [birbified/discord-giveaway#4]
When I create a drop, the drop embed does not send until someone has sent a message in that channel. How can I make it so that the drop embed automatically sends to that channel?

![image](https://user-images.githubusercontent.com/67352978/102529162-86ac8c00-406d-11eb-8789-21665325f137.png)
![image](https://user-images.githubusercontent.com/67352978/102529178-8c09d680-406d-11eb-9bfb-f074f98c0601.png)

**Comment by Cy1der** [comment]
My discord is ${Cy1der}#0001
Dm's open
If you have a fix, I HIGHLY recommend you dm me on discord instead of replying here

**Comment by Gav-King** [comment]
That's intentional. Use it to get your chat active maybe.
